openapi: 3.0.0
info:
  description: API for Pollenexchange Operations
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Nepflow Pollenexchange
  version: 1.0.0
servers:
- url: http://localhost:4200/api
tags:
- description: Operations to manage and retrive Users
  name: Pollenexchange
paths:
  /pollenexchange/pollenoffers/dates:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
          description: ..
        "404":
          description: error
      summary: return stored dates (Month-Year)
      tags:
      - Pollenexchange
      x-accepts:
      - application/json
      x-tags:
      - tag: Pollenexchange
  /pollenexchange/pollenoffers/open:
    get:
      parameters:
      - description: "if dates is not send, the current date in germany will be used\
          \ (date in Format MM-YYY)"
        explode: true
        in: query
        name: dates
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/PollenOfferDateContainerDTO"
                type: array
          description: ..
        "404":
          description: error
      summary: return open PollenOffers by Month-Year
      tags:
      - Pollenexchange
      x-accepts:
      - application/json
      x-tags:
      - tag: Pollenexchange
  /pollenexchange/{username}/pollenoffers/open:
    get:
      parameters:
      - explode: false
        in: path
        name: username
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/PollenOfferDTO"
                type: array
          description: ..
        "404":
          description: error
      summary: return all open PollenOffers of the user
      tags:
      - Pollenexchange
      x-accepts:
      - application/json
      x-tags:
      - tag: Pollenexchange
  /pollenexchange/trades/dates:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
          description: ..
        "404":
          description: error
      summary: return stored dates (Month-Year)
      tags:
      - Pollenexchange
      x-accepts:
      - application/json
      x-tags:
      - tag: Pollenexchange
  /pollenexchange/{username}/trades:
    get:
      parameters:
      - description: "if dates is not send, the current date in germany will be used\
          \ (date in Format MM-YYY)"
        explode: true
        in: query
        name: dates
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - explode: false
        in: path
        name: username
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/TradeDateContainerDTO"
                type: array
          description: ..
        "404":
          description: error
      summary: return all Trades and their status of the currently logged in user
      tags:
      - Pollenexchange
      x-accepts:
      - application/json
      x-tags:
      - tag: Pollenexchange
  /pollenexchange/create/trade:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TradeCreationDTO"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TradeDTO"
          description: Trade created successfully.
        "404":
          description: error  e.g userId and OfferId are wrong
      summary: create a Trade
      tags:
      - Pollenexchange
      x-content-type: application/json
      x-accepts:
      - application/json
      x-tags:
      - tag: Pollenexchange
  /pollenexchange/trade/{tradeId}:
    put:
      parameters:
      - explode: false
        in: path
        name: tradeId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TradeAnswerDTO"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TradeDTO"
          description: Trade created successfully.
        "404":
          description: error
      summary: accept or refuse a trade
      tags:
      - Pollenexchange
      x-content-type: application/json
      x-accepts:
      - application/json
      x-tags:
      - tag: Pollenexchange
components:
  parameters:
    offerId:
      explode: false
      in: path
      name: offerId
      required: true
      schema:
        type: string
      style: simple
    tradeId:
      explode: false
      in: path
      name: tradeId
      required: true
      schema:
        type: string
      style: simple
    username:
      explode: false
      in: path
      name: username
      required: true
      schema:
        type: string
      style: simple
    dates:
      description: "if dates is not send, the current date in germany will be used\
        \ (date in Format MM-YYY)"
      explode: true
      in: query
      name: dates
      required: false
      schema:
        items:
          type: string
        type: array
      style: form
  schemas:
    TradeAnswerDTO:
      example:
        acceptTrade: true
      properties:
        acceptTrade:
          type: boolean
      type: object
    TradeCreationDTO:
      example:
        userInitiatedOffer: userInitiatedOffer
        userRequestedOffer: userRequestedOffer
        userInitiated: userInitiated
        userRequested: userRequested
      properties:
        userInitiated:
          type: string
        userInitiatedOffer:
          type: string
        userRequested:
          type: string
        userRequestedOffer:
          type: string
      type: object
    UserDTO:
      example:
        country: country
        username: username
      properties:
        username:
          type: string
        country:
          type: string
      type: object
    PollenOfferDTO:
      example:
        seller: seller
        sex: sex
        nepenthesName: nepenthesName
        location: location
        id: id
        cloneId: cloneId
        user:
          country: country
          username: username
        pollenOfferOpenedDate: 2000-01-23
        imageLocation: imageLocation
      properties:
        id:
          type: string
        user:
          $ref: "#/components/schemas/UserDTO"
        nepenthesName:
          type: string
        cloneId:
          type: string
        sex:
          type: string
        location:
          type: string
        seller:
          type: string
        imageLocation:
          type: string
        pollenOfferOpenedDate:
          format: date
          type: string
      type: object
    PollenOfferDateContainerDTO:
      example:
        date: date
        pollenOffers:
        - seller: seller
          sex: sex
          nepenthesName: nepenthesName
          location: location
          id: id
          cloneId: cloneId
          user:
            country: country
            username: username
          pollenOfferOpenedDate: 2000-01-23
          imageLocation: imageLocation
        - seller: seller
          sex: sex
          nepenthesName: nepenthesName
          location: location
          id: id
          cloneId: cloneId
          user:
            country: country
            username: username
          pollenOfferOpenedDate: 2000-01-23
          imageLocation: imageLocation
      properties:
        date:
          description: MM-YYYY
          type: string
        pollenOffers:
          items:
            $ref: "#/components/schemas/PollenOfferDTO"
          type: array
      type: object
    TradeDTO:
      example:
        RequestedOffer:
          seller: seller
          sex: sex
          nepenthesName: nepenthesName
          location: location
          id: id
          cloneId: cloneId
          user:
            country: country
            username: username
          pollenOfferOpenedDate: 2000-01-23
          imageLocation: imageLocation
        InitiatedOffer:
          seller: seller
          sex: sex
          nepenthesName: nepenthesName
          location: location
          id: id
          cloneId: cloneId
          user:
            country: country
            username: username
          pollenOfferOpenedDate: 2000-01-23
          imageLocation: imageLocation
        tradeOpenedDate: 2000-01-23
        id: id
        status: status
      properties:
        id:
          type: string
        status:
          type: string
        InitiatedOffer:
          $ref: "#/components/schemas/PollenOfferDTO"
        RequestedOffer:
          $ref: "#/components/schemas/PollenOfferDTO"
        tradeOpenedDate:
          format: date
          type: string
      type: object
    TradeDateContainerDTO:
      example:
        date: date
        trades:
        - RequestedOffer:
            seller: seller
            sex: sex
            nepenthesName: nepenthesName
            location: location
            id: id
            cloneId: cloneId
            user:
              country: country
              username: username
            pollenOfferOpenedDate: 2000-01-23
            imageLocation: imageLocation
          InitiatedOffer:
            seller: seller
            sex: sex
            nepenthesName: nepenthesName
            location: location
            id: id
            cloneId: cloneId
            user:
              country: country
              username: username
            pollenOfferOpenedDate: 2000-01-23
            imageLocation: imageLocation
          tradeOpenedDate: 2000-01-23
          id: id
          status: status
        - RequestedOffer:
            seller: seller
            sex: sex
            nepenthesName: nepenthesName
            location: location
            id: id
            cloneId: cloneId
            user:
              country: country
              username: username
            pollenOfferOpenedDate: 2000-01-23
            imageLocation: imageLocation
          InitiatedOffer:
            seller: seller
            sex: sex
            nepenthesName: nepenthesName
            location: location
            id: id
            cloneId: cloneId
            user:
              country: country
              username: username
            pollenOfferOpenedDate: 2000-01-23
            imageLocation: imageLocation
          tradeOpenedDate: 2000-01-23
          id: id
          status: status
      properties:
        date:
          description: MM-YYYY
          type: string
        trades:
          items:
            $ref: "#/components/schemas/TradeDTO"
          type: array
      type: object
